"""add_google_login_and_multi_assignees

Revision ID: 828705d66d1b
Revises: 4ec87f02b002
Create Date: 2026-06-04 13:16:12.533385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '828705d66d1b'
down_revision = '4ec87f02b002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignees_task_id'), 'task_assignees', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_assignees_user_id'), 'task_assignees', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('is_personal', sa.Boolean(), server_default='0', nullable=False))
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), server_default='local', nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###

    # Data migration: copy existing assigned_to values to task_assignees junction table
    import uuid
    from datetime import datetime, timezone
    meta = sa.MetaData()
    task_assignees_table = sa.Table(
        'task_assignees', meta,
        sa.Column('id', sa.Uuid(), primary_key=True),
        sa.Column('task_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False)
    )
    tasks_table = sa.Table(
        'tasks', meta,
        sa.Column('id', sa.Uuid(), primary_key=True),
        sa.Column('assigned_to', sa.Uuid(), nullable=True)
    )
    connection = op.get_bind()
    results = connection.execute(
        sa.select(tasks_table.c.id, tasks_table.c.assigned_to).where(tasks_table.c.assigned_to.is_not(None))
    ).all()
    for task_id, assigned_to in results:
        if task_id and assigned_to:
            connection.execute(
                task_assignees_table.insert().values(
                    id=uuid.uuid4(),
                    task_id=task_id,
                    user_id=assigned_to,
                    assigned_at=datetime.now(timezone.utc)
                )
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_column('tasks', 'is_personal')
    op.drop_column('tasks', 'start_date')
    op.drop_index(op.f('ix_task_assignees_user_id'), table_name='task_assignees')
    op.drop_index(op.f('ix_task_assignees_task_id'), table_name='task_assignees')
    op.drop_table('task_assignees')
    # ### end Alembic commands ###
